from enum import StrEnum

class SupportedParameters(StrEnum):
    TOOL_CHOICE = "tool_choice"
    VERBOSITY = "verbosity"
    LOGIT_BIAS = "logit_bias"
    REPETITION_PENALTY = "repetition_penalty"
    FREQUENCY_PENALTY = "frequency_penalty"
    MAX_TOKENS = "max_tokens"
    REASONING = "reasoning"
    TOP_P = "top_p"
    TOP_A = "top_a"
    PRESENCE_PENALTY = "presence_penalty"
    MAX_COMPLETION_TOKENS = "max_completion_tokens"
    STRUCTURED_OUTPUTS = "structured_outputs"
    MIN_P = "min_p"
    STOP = "stop"
    TOP_LOGPROBS = "top_logprobs"
    TOOLS = "tools"
    SEED = "seed"
    TOP_K = "top_k"
    INCLUDE_REASONING = "include_reasoning"
    PARALLEL_TOOL_CALLS = "parallel_tool_calls"
    REASONING_EFFORT = "reasoning_effort"
    LOGPROBS = "logprobs"
    WEB_SEARCH_OPTIONS = "web_search_options"
    RESPONSE_FORMAT = "response_format"
    TEMPERATURE = "temperature"